"""Deterministic fact collector package for Spring Boot services."""

from .models import (
    ApiEndpoint,
    BuildFacts,
    ConfigEntry,
    CustomMetricFact,
    DatabaseTableFact,
    DatastoreFacts,
    DeploymentFacts,
    DownstreamDependencyFact,
    HealthAndMetricsFacts,
    KafkaConsumerFact,
    KafkaFacts,
    KafkaProducerFact,
    RepositoryInterfaceFact,
    ResilienceFact,
    ScanManifest,
    ServiceFacts,
    ServiceMeta,
    SourceEvidence,
    ValidationRule,
)
from .service_collector import ServiceFactsCollector, collect_service_facts, save_service_facts

__all__ = [
    "SourceEvidence",
    "ServiceMeta",
    "BuildFacts",
    "ConfigEntry",
    "ApiEndpoint",
    "ValidationRule",
    "KafkaConsumerFact",
    "KafkaProducerFact",
    "KafkaFacts",
    "DatabaseTableFact",
    "RepositoryInterfaceFact",
    "DatastoreFacts",
    "DownstreamDependencyFact",
    "ResilienceFact",
    "CustomMetricFact",
    "HealthAndMetricsFacts",
    "DeploymentFacts",
    "ScanManifest",
    "ServiceFacts",
    "ServiceFactsCollector",
    "collect_service_facts",
    "save_service_facts",
]
